#!/bin/bash

set -ev

echo This script sets up a virtual environment for the app

# ensure we are in the proper directory
test -f install/create_venv

rm -rf venv

python3 -m venv venv
source venv/bin/activate

pip install --upgrade pip

# echo apparently we need to install wheel in order to get binary python packages
pip install --upgrade wheel

pip install -r requirements.txt
